version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore ./VisitingNursesSystem.sln
build:
  project: ./VisitingNursesSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: 
after_test: 
