version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
before_build:
  - cmd: nuget restore ./VisitingNursesSystem.sln
build:
  project: ./VisitingNursesSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: sX5Y+j2YEDt/k4WsYQmkHZuhmR+Ukrd6/eeaHDGy3Xut3GR1g30xabHCwTF8AbwJ
after_test: 
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:VNS.Web.Tests\bin\Release\VNS.Web.Tests.dll" -output:coverage.xml
        
  - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%
