// <auto-generated />
namespace VNS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Datamodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datamodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201710020632343_Data models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
